---
title: "Johnson Lab 2"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(plyr)
```

Question1
```{r}
set.seed(5)
dice <- c("1","2","3","4","5","6")
fair_rollings <- replicate(8, sample(dice, 100, replace = TRUE)) 
fair_rollings_df <- data.frame(fair_rollings)
colnames(fair_rollings_df) <- c('first', 
 'second',
'third', 
'fourth', 
'fifth', 
'sixth', 
'seventh', 
'eighth')
clean_rollings <- data.frame(matrix('', ncol = 7, nrow = 0))
colnames(clean_rollings) <- c('names', 'one', 'two','three','four','five','six')
for (col in names(fair_rollings_df)){
 one <- sum(fair_rollings_df[[col]] == '1') 
 two <- sum(fair_rollings_df[[col]] == '2') 
 three <- sum(fair_rollings_df[[col]] == '3') 
 four <- sum(fair_rollings_df[[col]] == '4') 
 five <- sum(fair_rollings_df[[col]] == '5') 
 six <- sum(fair_rollings_df[[col]] == '6') 
 row_df <- data.frame('names' = col,
 'one' = one, 
'two' = two, 
'three' = three, 
'four' = four, 
'five' = five, 
'six' = six)
clean_rollings <- rbind(clean_rollings, row_df) }
clean_rollings
```
Question 2
```{r}
tidy_rollings <- data.frame(matrix('', ncol = 7, nrow = 0))
colnames(tidy_rollings) <- c('names', 'one', 'two','three','four','five','six')
for (col in names(fair_rollings_df)){ 
  row_df <- data.frame('trial' = col,
                       'one' = fair_rollings_df[[col]] == '1', 
                       'two' = fair_rollings_df[[col]] == '2', 
                       'three' = fair_rollings_df[[col]] == '3', 
                       'four' = fair_rollings_df[[col]] == '4', 
                       'five' = fair_rollings_df[[col]] == '5', 
                       'six' = fair_rollings_df[[col]] == '6')
  tidy_rollings <- rbind(tidy_rollings, row_df) 
}
ggplot(tidy_rollings) +
  geom_bar(aes( x=tidy_rollings$trial, fill=four))+ 
  scale_fill_discrete(name = 'Whether it is four')+ 
  labs(title='Results of 8 trials of 100 rollings of a fair die',
       x='Trial', 
       y='Proportion')
```

```{r}
set.seed(5)
biased_probability<-c(0.14, 0.14, 0.14, 0.3, 0.14, 0.14)
biased_rollings<- replicate(8, sample(dice, 100, replace = TRUE, prob = biased_probability))
biased_rollings_df <- data.frame(biased_rollings)
colnames(biased_rollings_df) <- c('first', 
                                  'second',
                                  'third', 
                                  'fourth', 
                                  'fifth', 
                                  'sixth', 
                                  'seventh', 
                                  'eighth')
clean_rollings <- data.frame(matrix('', ncol = 7, nrow = 0))
colnames(clean_rollings) <- c('names', 'one', 'two','three','four','five','six')
for (col in names(biased_rollings_df)){
  one <- sum(biased_rollings_df[[col]] == '1') 
  two <- sum(biased_rollings_df[[col]] == '2') 
  three <- sum(biased_rollings_df[[col]] == '3') 
  four <- sum(biased_rollings_df[[col]] == '4') 
  five <- sum(biased_rollings_df[[col]] == '5') 
  six <- sum(biased_rollings_df[[col]] == '6') 
  row_df <- data.frame('names' = col,
                       'one' = one, 
                       'two' = two, 
                       'three' = three, 
                       'four' = four, 
                       'five' = five, 
                       'six' = six)
  clean_rollings <- rbind(clean_rollings, row_df) }
clean_rollings
```
Question 3
```{r}
tidy_rollings <- data.frame(matrix('', ncol = 7, nrow = 0))
colnames(tidy_rollings) <- c('names', 'one', 'two','three','four','five','six')
for (col in names(biased_rollings_df)){ 
  row_df <- data.frame('trial' = col,
                       'one' = biased_rollings_df[[col]] == '1', 
                       'two' = biased_rollings_df[[col]] == '2', 
                       'three' = biased_rollings_df[[col]] == '3', 
                       'four' = biased_rollings_df[[col]] == '4', 
                       'five' = biased_rollings_df[[col]] == '5', 
                       'six' = biased_rollings_df[[col]] == '6')
  tidy_rollings <- rbind(tidy_rollings, row_df) 
}
ggplot(tidy_rollings) +
  geom_bar(aes( x=tidy_rollings$trial, fill=four))+ 
  scale_fill_discrete(name = 'Whether it is four')+ 
  labs(title='Results of 8 trials of 100 rollings of a biased die',
       x='Trial', 
       y='Proportion')
```
Question 4
```{r}
rolling_4 <- function(B){ 
  rolling_4 <- function(B){ 
    dice <- c('1', '2', '3', '4', '5', '6')
    rollings <- replicate(B, sample(dice, 1, replace = TRUE))
    rolling_df <- data.frame(rollings) 
    prop <- sum(rolling_df$rolling == "4") / length(rolling_df$rolling) 
    return(prop)
  }
  lst <- lapply(seq(1, B), rolling_4) 
  df <- ldply(lst, data.frame) 
  names(df) <- c('prop')
  df$n <- seq(1, length(df$prop))
  ggplot(df, aes(x = n, y = prop)) + 
    geom_line(color = 'red') + 
    geom_hline(yintercept = 0.167,
               linetype = 'dashed') + 
    theme_bw() +
    labs(x = 'Number of rollings',
         y = 'Proportion ',
         title = 'what is the proportion of rollings that are 4') +
    xlim(1, B) +
    ylim(0, 1)
}
set.seed(5)

ggarrange(rolling_4(5), rolling_4(10), rolling_4(100), rolling_4(1000))
```
Question 5
```{r}
rolling_4 <- function(B){ 
  rolling_4 <- function(B){ 
    dice <- c('1', '2', '3', '4', '5', '6')
    biased_probability<-c(0.14, 0.14, 0.14, 0.3, 0.14, 0.14)
    rollings <- replicate(B, sample(dice, 1, replace = TRUE, prob = biased_probability))
    rolling_df <- data.frame(rollings) 
    prop <- sum(rolling_df$rolling == "4") / length(rolling_df$rolling) 
    return(prop)
  }
  lst <- lapply(seq(1, B), rolling_4) 
  df <- ldply(lst, data.frame) 
  names(df) <- c('prop')
  df$n <- seq(1, length(df$prop))
  ggplot(df, aes(x = n, y = prop)) + 
    geom_line(color = 'red') + 
    geom_hline(yintercept = 0.3,
               linetype = 'dashed') + 
    theme_bw() +
    labs(x = 'Number of rollings',
         y = 'Proportion ',
         title = 'what is proportion of rollings that are 4') +
    xlim(1, B) +
    ylim(0, 1)
}
set.seed(5)

ggarrange(rolling_4(5), rolling_4(10), rolling_4(100), rolling_4(1000))
```

